### ISSUE TITLE
[Quest] Libram of rapidity cannot be turned in

### ISSUE THREAD

**Issue by Critboys** [VortexPrecision/PrecisionWoW#273] opened 2021-01-05 12:48 UTC
Libram of rapidity cannot be turned in,by default Elven legends quest should be completed first in order this quest to work,but that doesnt work neither.

**Comment by Broker-Precision** [comment] 2021-01-23 21:12
Please Comfirm, I can't reproduce the issue with being unable to hand in Libram of Rapidity quest.
And confirmed Elven legends can be completed - I corrected the pre-quests required to pick up Libram quests from Lydros

**Comment by Broker-Precision** [comment] 2021-01-26 17:20
No reponse, Closing ticket.

**Closed as completed by Broker-Precision** 2021-01-26 17:20 UTC
