### ISSUE TITLE
Human Racial Diplomacy Not Working

### ISSUE THREAD

**Issue by cromne** [VortexPrecision/PrecisionWoW#197] opened 2020-12-21 14:22 UTC
Human racial, Diplomacy isn't working and is not giving the bonus reputation as evidenced by the following screenshots
<blockquote class="imgur-embed-pub" lang="en" data-id="a/FGUYRY0"  ><a href="//imgur.com/a/FGUYRY0">Reputation Bug</a></blockquote>

I only gained 100 reputation instead of 110 from the 10% racial bonus.

**Comment by VortexPrecision** [comment] 2020-12-24 08:15
Can't reproduce. Tested on this quest and this was the result:
(this quests awards 500 reputation)
![image](https://user-images.githubusercontent.com/71529592/103073730-067fac80-45c0-11eb-8416-abe96d0fa75d.png)

Although i found that in certain cases this is not working (like spells or even BG rep) and that is fixed in the next update.

**Closed as completed** 2020-12-24 08:16 UTC
